name: layout_manager
description: Helper
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=3.3.22"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  connectivity_plus: ^6.0.5
  parse_server_sdk: ^7.0.0
  shared_preferences: ^2.2.0
  webview_flutter: ^4.8.0
  flutter_local_notifications: ^17.2.1+2
  dio: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.layout_manager.layout_manager
        pluginClass: LayoutManagerPlugin
      ios:
        pluginClass: LayoutManagerPlugin
      windows:
        pluginClass: LayoutManagerPluginCApi

